name: Build

permissions:
  contents: write  # Release 생성을 위해 필요

on:
  push:
    branches: [ "main" ]  # main 브랜치 푸시 시 실행
  workflow_dispatch:  # 수동 실행 가능

jobs:
  call-build-workflow:
    uses: ./.github/workflows/reusable_build.yml
    with:
      build_number: ${{ github.run_number }}
